apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    name: consul
spec:
  clusterIP: None
  ports:
    - name: defult
      port: 80 #8500
      targetPort: 8500
    - name: http
      port: 8500
      targetPort: 8500
    - name: https
      port: 8443
      targetPort: 8443
    - name: rpc
      port: 8400
      targetPort: 8400
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
      targetPort: 8301
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
      targetPort: 8301
    - name: serfwan-tcp
      protocol: "TCP"
      port: 8302
      targetPort: 8302
    - name: serfwan-udp
      protocol: "UDP"
      port: 8302
      targetPort: 8302
    - name: server
      port: 8300
      targetPort: 8300
    - name: consuldns
      port: 8600
      targetPort: 8600
  selector:
    app: consul
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: consul
  # annotations:
  #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    # - host: itest.icoastline.cn
    #   http:
    #     paths: 
    #     - path: /consul
    #       backend:
    #         serviceName: consul 
    #         servicePort: 8500
    - host: consul.icoastline.cn
      http:
        paths: 
        - path: /
          backend:
            serviceName: consul 
            servicePort: 80